### Create a new user
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "name": "Sofia D'ávila Sobrinho",
  "cpf": "613.048.009-11",
  "birth_date": "1998-06-11",
  "email": "rodolfo.matos@gil.com.br",
  "phone": "(49) 98923-9978",
  "cep": "70585-807",
  "state": "AP",
  "city": "Irene d'Oeste",
  "neighborhood": "do Norte",
  "address": "Avenida Isadora Amaral, 82",
  "status": 1,
}


### Read all users registered (only active users)
GET http://localhost:8989/api/users


### Show a user (only active users)
GET http://localhost:8000/api/users/1


### Update a user
PUT http://localhost:8000/api/users/2
Content-Type: application/json

{
  "name": "New name user"
}


### Delete a user (only active users)
DELETE http://localhost:8000/api/users/1